import React,{useEffect,useState} from "react"; import{createRoot}from"react-dom/client"; import{Activity,Boxes,CheckCircle2,Clock3,Plus,Server,Skull,Workflow}from"lucide-react";
import{api,Job,Metrics,Project,Queue,token}from"./api"; import"./index.css";
const empty:Metrics={total_jobs:0,queued:0,running:0,succeeded:0,failed:0,dead:0,active_workers:0,success_rate:0};
function Login({done}:{done:()=>void}){
 const[email,setEmail]=useState("admin@example.com"),[password,setPassword]=useState("password123"),[error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();try{const r=await api<{access_token:string}>("/auth/login",{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("token",r.access_token);done()}catch(x){setError((x as Error).message)}}
 return <main className="grid min-h-screen place-items-center p-6"><form onSubmit={submit} className="card w-full max-w-md space-y-5"><div><div className="mb-4 inline-flex rounded-xl bg-lime p-3 text-ink"><Workflow/></div><h1 className="text-3xl font-bold">Chronos</h1><p className="mt-1 text-slate-400">Distributed orchestration control plane</p></div><input className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/>{error&&<p className="text-sm text-red-400">{error}</p>}<button className="btn w-full">Sign in</button></form></main>
}
function Dashboard(){
 const[projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState(""),[queues,setQueues]=useState<Queue[]>([]),[queue,setQueue]=useState(""),[jobs,setJobs]=useState<Job[]>([]),[metrics,setMetrics]=useState(empty),[show,setShow]=useState(false),[error,setError]=useState("");
 useEffect(()=>{api<Project[]>("/projects").then(p=>{setProjects(p);if(p[0])setProject(p[0].id)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!project)return;Promise.all([api<Queue[]>(`/queues?project_id=${project}`),api<Metrics>(`/metrics?project_id=${project}`)]).then(([q,m])=>{setQueues(q);setMetrics(m);if(q[0])setQueue(q[0].id)})},[project]);
 useEffect(()=>{if(queue)api<Job[]>(`/jobs?queue_id=${queue}`).then(setJobs)},[queue]);
 async function addJob(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);await api("/jobs",{method:"POST",body:JSON.stringify({queue_id:queue,name:fd.get("name"),priority:Number(fd.get("priority")),payload:{source:"dashboard"}})});setShow(false);setJobs(await api<Job[]>(`/jobs?queue_id=${queue}`))}
 const cards=[[metrics.total_jobs,"Total jobs",Boxes],[metrics.queued,"Queued",Clock3],[metrics.running,"Running",Activity],[metrics.succeeded,"Succeeded",CheckCircle2],[metrics.dead,"Dead letter",Skull],[metrics.active_workers,"Workers",Server]] as const;
 return <div className="min-h-screen"><header className="border-b border-white/10 bg-panel/70 px-6 py-4 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><span className="rounded-lg bg-lime p-2 text-ink"><Workflow size={20}/></span><b className="text-xl">Chronos</b><span className="rounded-full bg-emerald-400/10 px-2 py-1 font-mono text-xs text-emerald-400">SYSTEM HEALTHY</span></div><button onClick={()=>{localStorage.clear();location.reload()}} className="text-sm text-slate-400">Sign out</button></div></header>
 <main className="mx-auto max-w-7xl space-y-7 p-6"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-widest text-lime">Control plane</p><h1 className="mt-2 text-3xl font-bold">Operations overview</h1></div><div className="flex gap-3"><select className="input" value={project} onChange={e=>setProject(e.target.value)}>{projects.map(x=><option className="bg-panel" value={x.id} key={x.id}>{x.name}</option>)}</select><button className="btn flex items-center gap-2" disabled={!queue} onClick={()=>setShow(true)}><Plus size={17}/>New job</button></div></section>
 {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-red-300">{error}</div>}<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{cards.map(([n,label,Icon])=><div className="card" key={label}><Icon className="mb-5 text-slate-500" size={20}/><div className="text-3xl font-bold">{n}</div><div className="text-sm text-slate-400">{label}</div></div>)}</section>
 <section className="card overflow-hidden p-0"><div className="flex items-center justify-between border-b border-white/10 p-5"><h2 className="font-semibold">Recent jobs</h2><select className="input w-48" value={queue} onChange={e=>setQueue(e.target.value)}>{queues.map(q=><option className="bg-panel" value={q.id} key={q.id}>{q.name}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-500"><tr>{["Job","Status","Priority","Attempts","Scheduled"].map(x=><th className="px-5 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{jobs.map(j=><tr className="border-t border-white/5" key={j.id}><td className="px-5 py-4"><b>{j.name}</b><div className="font-mono text-xs text-slate-500">{j.id.slice(0,8)}</div></td><td className="px-5"><span className="rounded-full bg-white/5 px-2 py-1">{j.status}</span></td><td className="px-5">{j.priority}</td><td className="px-5">{j.attempt_count}/{j.max_attempts}</td><td className="px-5 text-slate-400">{new Date(j.scheduled_at).toLocaleString()}</td></tr>)}</tbody></table>{!jobs.length&&<p className="p-10 text-center text-slate-500">No jobs in this queue yet.</p>}</div></section></main>
 {show&&<div className="fixed inset-0 grid place-items-center bg-black/70 p-4"><form onSubmit={addJob} className="card w-full max-w-md space-y-4"><h2 className="text-xl font-bold">Submit job</h2><input required name="name" className="input" placeholder="Job name"/><input name="priority" type="number" defaultValue="0" className="input" placeholder="Priority"/><div className="flex justify-end gap-3"><button type="button" onClick={()=>setShow(false)} className="px-4">Cancel</button><button className="btn">Submit</button></div></form></div>}</div>
}
function App(){const[auth,setAuth]=useState(!!token());return auth?<Dashboard/>:<Login done={()=>setAuth(true)}/>}createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
